parameters:
#    medbac_user.example.class: Medbac\UserBundle\Example

services:
#    medbac_user.example:
#        class: %medbac_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
