<?php

namespace MedBac\FormationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BijouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BijouRepository extends EntityRepository
{
    /**
     * Retourne la liste des films correspondant au genre passé en paramètre (id)
     * Si aucun genre n'est spécifié, la liste de tous les films est renvoyée.
     * @param int $idGenre Id du genre à rechercher
     * @return MedBacFormationBundle\Entity\Film[] Liste des films du genre demandé
     */
    public function findByGenre($idGenre=0)
    {       
       /* Création de la requète avec le query builder */
       $queryBuilder = $this->_em->createQueryBuilder();      
       $queryBuilder->select("f, g")
                    ->from("MedBacFormationBundle:Bijou", "f")
                    ->leftJoin("f.listeDesGenres", "g");
               
        
       /* Si on reçoit un id de genre valide alors on recherche les Films de ce genre là uniquement */
       if((int)$idGenre > 0) {
           $queryBuilder->where("g.id=:x")->setParameter("x", (int)$idGenre);
       }
       /* Puis on retourne la liste des films du genre demandé */
       return $queryBuilder->getQuery()->getResult();
    }
     
    /**
     * Retourne le nombre de film au total
     * @return int Renvoie le nombre de films total
     */
    public function countAll() {
        
         
        $queryBuilder = $this->_em->createQueryBuilder();      
       $queryBuilder->select("count(f) as total")
                    ->from("MedBacFormationBundle:Bijou", "f");
      
       return $queryBuilder->getQuery()->getSingleScalarResult();
    }
    
    public function getSerachResult($criteria) {
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select("f")
                ->from("MedBacFormationBundle:Bijou", "f");


        $queryBuilder->where("f.titre = (:x)")->setParameter("x", $criteria['quantite'])
        ->orWhere("f.prix = (:x)")->setParameter("x", $criteria['quantite']);
             
        return $queryBuilder->getQuery()->getResult();
    }
}
